04_dense_layer/rtl/mac_unit.sv
04_dense_layer/rtl/dense_layer.sv
04_dense_layer/rtl/feature_buffer.sv
04_dense_layer/rtl/layer_buffer.sv
04_dense_layer/rtl/weight_memory.sv
04_dense_layer/rtl/bias_memory.sv
04_dense_layer/rtl/relu_layer.sv
04_dense_layer/rtl/requantize_layer.sv
05_mlp_core/rtl/mlp_controller.sv
05_mlp_core/rtl/mlp_core.sv
05_mlp_core/rtl/soh_out_reg.sv
05_mlp_core/rtl/mlp_top.sv
06_uart/uart_rx
06_uart/uart_packet_rx
06_uart/uart_tx
07_top_integration/rtl/reset_sync.sv
07_top_integration/rtl/uart_packet_tx.sv
07_top_integration/rtl/fpga_top.sv
